# Activation Function

Activation function is applied to the output of a neuron which modifies it.

There are 2 types of Activation function:-

## Linear Activation function

Linear activation is simply creating a linear equation of the output. These are usually applied on output layer of a regression problem.


## Non linear activation function

A non linear activation function helps in estimating non linear functions. Few non linear functions are sigmoid, ReLU, leaky ReLU, etc.


ReLU is given as:-

$y = x\ \ if\ \ x > 0 $ and  

$y = 0\ \ if\ \ x \leq 0$

In [1]:
import numpy as np
from nnfs.datasets import spiral_data
import nnfs

In [2]:
## ReLU function:-

inputs = [0, 2, -1, 8, -3.5, 6, 7, -0.75]
output = []

for i in inputs:
    if i <= 0:
        output.append(0)
    if i > 0:
        output.append(i)

print(output)

[0, 2, 0, 8, 0, 6, 7, 0]


We can write the ReLU function in short as 

In [3]:
output = []

for i in inputs:
    output.append(max(0,i))

print(output)

[0, 2, 0, 8, 0, 6, 7, 0]


In [4]:
output = np.maximum(0, inputs)
print(output)

[0. 2. 0. 8. 0. 6. 7. 0.]


We will now add Relu function to our neurons from previous exercise

In [5]:

X, y = spiral_data(samples = 100, classes = 3)

In [6]:
class Dense_layer:

    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [7]:
class Activation_Relu:

    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [8]:
dense1 = Dense_layer(2,3)

dense1.forward(X)

In [9]:
activation1 = Activation_Relu()

activation1.forward(dense1.output)

In [10]:
print(activation1.output[:5])

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.17735785e-06 0.00000000e+00 5.10955779e-05]
 [2.54051010e-05 0.00000000e+00 1.11775312e-04]
 [0.00000000e+00 0.00000000e+00 9.96140042e-05]
 [0.00000000e+00 3.13989540e-05 0.00000000e+00]]


We can see that negative values are clipped at 0.

## Softmax Activation function

$ y = \frac{exp^{z_{ij}}}{\sum_{l=1}^{L} exp^{z_{il}}} $


For example

In [11]:
input_layer = [4.8, 1.21, 2.385]

exp_input = np.exp(input_layer)

norm_base = sum(exp_input)

In [12]:
# Output after softmax activation function
norm_values = exp_input/norm_base

In [13]:
print(norm_values)
print(sum(norm_values))

[0.89528266 0.02470831 0.08000903]
0.9999999999999999


### Disadvantage of Softmax

One of the disadvantage is that taking exponential of a large number might result in infinite value and hence the neuron might explode. For e.g.

In [14]:
np.exp(1000)

<ipython-input-14-47a6eab891c2>:1: RuntimeWarning: overflow encountered in exp
  np.exp(1000)


inf

We know the exponential function tends toward 0 as its input value approaches negative infinity, and the output is 1 when the input is 0. We can use this property to prevent the exponential function from overflowing. We can subtract the largest value from a list of input values.

We will now use Softmax in a layer above Relu layer.

In [15]:
X, y = spiral_data(samples = 100, classes = 3)

class Dense_layer:

    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_Relu:

    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


class Activation_softmax:
    
    def forward(self, inputs):

        exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        probabilities = exp_values/np.sum(exp_values, axis = 1, keepdims = True)
        self.output = probabilities

In [16]:
#Creating a dense layer with 3 neuron and 2 input features means 2 weights in each neuron
dense1 = Dense_layer(2,3)

# Making a forward pass in this layer
dense1.forward(X)

# applying a ReLU activation function to the output of the first layer
activation1 = Activation_Relu()

activation1.forward(dense1.output)

# Creating another layer with 3 neuron and 3 input layers
dense2 = Dense_layer(3,3)

#Making a forward pass in 2nd layer with output from 1st layer
dense2.forward(activation1.output)

#Applying softmax activation to the output
activation2 = Activation_softmax()

activation2.forward(dense2.output)

print(activation2.output[:5])


[[0.33333333 0.33333333 0.33333333]
 [0.33333336 0.33333338 0.33333327]
 [0.33333333 0.33333333 0.33333333]
 [0.33333337 0.33333386 0.33333277]
 [0.33333344 0.33333352 0.33333304]]
